---
- hosts: all
  become: yes

  tasks:
    - unarchive:
        src=files/raspberrypi2.zip
        dest=/opt/
        owner=root
        group=root
        mode=0644

    - file:
        path=/opt/raspberrypi_2.0/compile_rpi2
        owner=root
        group=root
        mode=0744

    - name: compiling arduPi
      shell: /opt/raspberrypi_2.0/compile_rpi2

    - name: erasing ttyAMA0
      replace:
        dest="{{ item.file }}"
        regexp="{{ item.to_delete }}"
      with_items:
        - { file: "/etc/inittab", to_delete: "ttyAMA0" }
        - { file: "/boot/cmdline.txt", to_delete: "console=ttyAMA0,115200" }

    - modprobe:
        name="{{ item }}
        state=present
      with_items:
        - "i2c-bcm2708"
        - "i2c-dev"

    - lineinfile:
        dest="/boot/cmdline.txt"
        line="dtparam={{ item }}"
        state=present
      with_items:
        - "i2c1=on"
        - "i2c_arm=on"

    - unarchive:
        src=files/sigfox_library_raspberrypi_v1.zip
        dest=/opt/
        owner=root
        group=root
        mode=0744

    - file:
        path=/home/pi/sigfox/src
        state=directory
        owner=pi
        group=pi
        mode=0755

    - shell: cp /opt/ardupi-apiSIGFOX//{{ item }} /home/pi/sigfox/src
      with_items:
        - ardupiSigfox/cookingSigfox.cpp
        - ardupiSigfox/cookingSigfox.h
        - ardupi-api/arduPi.h
        - ardupi-api/arduPi.o
        - ardupi-api/cookingUART.h
        - ardupi-api/cookingUART.cpp
        - ardupi-api/cookingUtils.h
        - ardupi-api/cookingUtils.cpp
        - ardupi-api/cookingClasses.h

    - copy:
        src=files/{{ item }}
        dest=/home/pi/sigfox/src
        owner=pi
        group=pi
        mode=0744
      with_items:
        - SeeedDHT.cpp
        - SeeedDHT.h

    - file:
        path=/home/pi/sigfox
        owner=pi
        group=pi
        recurse=yes

    - copy:
        src=files/makefile
        dest=/home/pi/sigfox
        owner=pi
        group=pi
        mode=0744

    - copy:
        src="files/{{ item }}"
        dest="/home/pi/sigfox"
        owner=pi
        group=pi
        mode=0744
      with_items:
        - 00-get_sigfox_modem_id.cpp
        - 01-send_sigfox_dummy_data.cpp
        - 02-light-leds.cpp
        - 03-print-luminance.cpp
        - 04-print-temperature-and-humidity.cpp
        - 05-detect-button-push.cpp
