---
- hosts: all
  sudo: yes

  vars:
    raspbian_sd : "{{ RASPBIAN_SD }}"
    wifi_pass : "{{ WIFI_PASS }}"

  tasks:
    - unarchive: src=files/raspberrypi2.zip dest=/opt/ owner=root group=root mode=0644
    - file: path=/opt/raspberrypi_2.0/compile_rpi2 owner=root group=root mode=0744
#    - shell: /opt/raspberrypi_2.0/compile_rpi2
    - lineinfile: dest="/etc/inittab"  regexp="ttyAMA0" state="absent"
    - replace: dest="/boot/cmdline.txt"  regexp="console=ttyAMA0,115200"
    - lineinfile: dest=/etc/modules line=i2c-bcm2708 state=present
    - lineinfile: dest="/etc/modules" line="i2c-dev" state="present"
    - lineinfile: dest=/boot/cmdline.txt line="dtparam=i2c1=on" state="present"
    - lineinfile: dest=/boot/cmdline.txt line="dtparam=i2c_arm=on" state="present"

    - unarchive: src=files/sigfox_library_raspberrypi_v1.zip dest=/opt/ owner=root group=root mode=0744
    - file: path=/home/pi/sigfox/src state=directory owner=pi group=pi mode=0755
    - shell: cp /opt/ardupi-apiSIGFOX//{{ item }} /home/pi/sigfox/src
      with_items:
        - ardupiSigfox/cookingSigfox.cpp
        - ardupiSigfox/cookingSigfox.h
        - ardupi-api/arduPi.h
        - ardupi-api/arduPi.o
        - ardupi-api/cookingUART.h
        - ardupi-api/cookingUART.cpp
        - ardupi-api/cookingUtils.h
        - ardupi-api/cookingUtils.cpp
        - ardupi-api/cookingClasses.h
    - file: path=/home/pi/sigfox owner=pi group=pi recurse=yes 
    - copy: src=files/makefile dest=/home/pi/sigfox owner=pi group=pi mode=0744
    - copy: src=files/00-get_sigfox_modem_id.cpp dest=/home/pi/sigfox owner=pi group=pi mode=0744
